### ISSUE TITLE
[BUG] Parity class __int__ method

### ISSUE THREAD

**Issue by spflueger** [ComPWA/expertsystem#146]
The `__int__` method in the `Parity` class should use `self.__value` instead of `self.value`.

I guess this bug never appeared because the `__int__`/`int()` functionality is never used. Hence, we might also consider removing this functionality.

**Comment by redeboer** [comment]
I'm not sure if this matters/changes anything. The `__int__` cast method now calls the `value` property instead of the `__value` attribute, which is not a problem (performance at most, perhaps?).

For the record, here are the lines in question:
https://github.com/ComPWA/expertsystem/blob/f98a7a9ebbc88505c098e3ea07d8f2920c3a7983/expertsystem/data.py#L30-L40

**Comment by spflueger** [comment]
Oh, I completely missed that... My bad

**Comment by redeboer** [comment]
Haha no problem. Btw, even though this function isn't tested (not sure about that actually), the class is checked by `mypy`, `pylint`, and `flake8`, which would have pointed out if this were a mistake.
