### ISSUE TITLE
Refactor conservation_rules module

### ISSUE THREAD

**Issue by redeboer** [ComPWA/expertsystem#53]
Requires #50

**Comment by spflueger** [comment]
So from playing around with Issue #130 and draft PR #194, the following things became clear:

* A  `Rule` class structure, which defines an interface, is needed. The reason is that rules not only define a function that verify the validity of some given facts (input arguments), but also conditions on which facts are needed for the rule to execute successfully.
=> Having a class allows to extract the requirements separately and solvers can use this to their advantage. (knowing exactly which variables to set in order to be able to call a rule)
* In order to get full static type support, the concept of dynamically creating arguments for the Rule functions is incompatible
=> Either use a list of `QuantumState` instances or separately define subset "dataclass" as arguments. The latter would be favorable. As the first thing give more room for errors on implementing the rules iteself
* In order to get the sphinx documentation working smoothly, I found that its best for users to define their rule as a class which implements the `Rule` interface. The method which performs the actual check has to be implemented in the class directly. However implementing condition logic is similar for all rules and can handled nicely via decorators.
